# Generated by Django 3.1.6 on 2021-02-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=50)),
                ('password', models.CharField(default=None, max_length=50)),
                ('name', models.CharField(default=None, max_length=50)),
                ('age', models.IntegerField(default=None)),
                ('address', models.CharField(default=None, max_length=50)),
                ('allergies', models.TextField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
