# Generated by Django 3.1.7 on 2021-03-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownuser',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
    ]
