# Generated by Django 3.1.7 on 2021-02-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='date',
            field=models.CharField(default='10.02', max_length=5),
        ),
        migrations.AddField(
            model_name='dinner',
            name='max_guests',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='dinner',
            name='time',
            field=models.CharField(default='16.00', max_length=5),
        ),
    ]
