# Generated by Django 3.1.6 on 2021-02-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0002_auto_20210223_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
