# Generated by Django 3.1.7 on 2021-03-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0003_auto_20210224_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='allergies',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
