# Generated by Django 3.1.6 on 2021-02-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0003_auto_20210224_1328'),
        ('dinners', '0003_auto_20210224_1422'),
    ]

    operations = [
    ]
