# Generated by Django 3.1.7 on 2021-03-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0004_dinner_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='category',
            field=models.CharField(default='Velg kategori', max_length=50),
        ),
    ]
