# Generated by Django 3.1.7 on 2021-03-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0004_merge_20210224_1458'),
        ('dinners', '0005_dinner_category'),
    ]

    operations = [
    ]
