# Generated by Django 3.1.6 on 2021-03-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0005_dinner_category'),
        ('dinners', '0004_merge_20210224_1458'),
    ]

    operations = [
    ]
