# Generated by Django 3.1.6 on 2021-03-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0007_auto_20210312_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinner',
            name='address',
        ),
        migrations.AlterField(
            model_name='dinner',
            name='place',
            field=models.CharField(default='', max_length=50),
        ),
    ]
