# Generated by Django 3.1.6 on 2021-03-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0007_auto_20210315_0916'),
        ('dinners', '0007_auto_20210315_1040'),
    ]

    operations = [
    ]
