# Generated by Django 3.1.7 on 2021-03-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0007_auto_20210311_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='number_of_guests',
            field=models.IntegerField(default=0),
        ),
    ]
