# Generated by Django 3.1.6 on 2021-03-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0008_merge_20210315_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='cost',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
