# Generated by Django 3.1.7 on 2021-03-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0008_dinner_number_of_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='guests',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
