# Generated by Django 3.1.6 on 2021-03-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0010_auto_20210325_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinner',
            name='cost',
        ),
    ]
