# Generated by Django 3.1.6 on 2021-03-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0010_auto_20210312_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='host_username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
