# Generated by Django 3.1.7 on 2021-03-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0011_dinner_host_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='place',
            field=models.CharField(default='', max_length=50),
        ),
    ]
