# Generated by Django 3.1.6 on 2021-03-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0011_remove_dinner_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
