# Generated by Django 3.1.6 on 2021-03-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0011_dinner_host_username'),
        ('dinners', '0008_auto_20210312_1545'),
    ]

    operations = [
    ]
