# Generated by Django 3.1.7 on 2021-03-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0012_merge_20210315_0754'),
        ('dinners', '0013_auto_20210315_0911'),
    ]

    operations = [
    ]
