# Generated by Django 3.1.6 on 2021-03-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0013_auto_20210325_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='cost_per_guest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
