# Generated by Django 3.1.6 on 2021-03-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0014_auto_20210331_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cost_per_guest',
            field=models.IntegerField(default=1),
        ),
    ]
