# Generated by Django 3.1.6 on 2021-03-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0015_auto_20210331_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinner',
            name='cost_per_guest',
        ),
    ]
