# Generated by Django 3.1.6 on 2021-03-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0015_merge_20210315_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinner',
            name='number_of_guests',
        ),
    ]
