# Generated by Django 3.1.6 on 2021-04-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0016_remove_dinner_cost_per_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='cost_per',
            field=models.IntegerField(default=1),
        ),
    ]
