# Generated by Django 3.1.6 on 2021-03-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0016_remove_dinner_number_of_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='available',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='dinner',
            name='number_of_guests',
            field=models.IntegerField(default=0),
        ),
    ]
