# Generated by Django 3.1.6 on 2021-04-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0017_dinner_cost_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='cost_per',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
