# Generated by Django 3.1.6 on 2021-03-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0017_auto_20210315_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='chat',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
