# Generated by Django 3.1.6 on 2021-04-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0018_auto_20210406_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='cost_per',
            field=models.IntegerField(blank=True),
        ),
    ]
