# Generated by Django 3.1.6 on 2021-04-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0021_auto_20210406_1605'),
        ('dinners', '0020_dinner_city'),
    ]

    operations = [
    ]
